name: CI

on:
  push:
    branches:
      - master # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t jz8132543/ebook-sender-bot:${{ github.sha }} .
          docker tag jz8132543/ebook-sender-bot:${{ github.sha }} jz8132543/ebook-sender-bot:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push jz8132543/ebook-sender-bot:latest
          docker push jz8132543/ebook-sender-bot:${{ github.sha }}

